services:
  db:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: toor
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --bind-address=0.0.0.0
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
  
volumes:
  mysql_data:
